### ISSUE TITLE
README file

### ISSUE THREAD

**Issue by goldcaddy77** [zuzusik/dx-campaign-creation-proto#1]
@zuzusik could you create a readme file for somebody that wants to run a local instance of the prototype?

**Comment by zuzusik** [comment]
Will do it today :+1:

**Comment by goldcaddy77** [comment]
:+1:

**Comment by zuzusik** [comment]
Done in https://github.com/zuzusik/dx-campaign-creation-proto/commit/ccb13052c5404fed78276efa69a2bca38761e5b0
